language: go

sudo: required

services:
  - docker

go:
  - 1.5

before_install:
  - sudo apt-get update
  - curl https://glide.sh/get | sh

install:
  - glide install -v

before_script:
  - docker version
  - make binary-linux-amd64
  - chmod +x bin/linux/amd64/local-persist
  - sudo ./bin/linux/amd64/local-persist &

script:
  - ./scripts/integration.sh
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7dc8b1b12ff5bd6c133e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
